#!/usr/bin/env bash
# This script checks if a given IP address is reachable by sending 5 ICMP packets. 
if [[ $# -eq 0 ]]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit 0
else
	ping -c 5 "$1"
fi
